import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import Error from "next/error";
import { tools } from "../../lib/tools";
import styles from "../../styles/DetailPage.module.css";

const ToolPage = () => {
  const router = useRouter();
  console.log(router.query);
  const tool = tools.find((tool) => tool.id === router.query.id);
  if (!tool) {
    return <Error statusCode={404} />;
  }

  const { name } = tool;

  return (
    <div className={styles.container}>
      <Head>
        <title>{name} | Asmbly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{name}</h1>
        <img
          className={styles.image}
          src={tool.image}
          alt={`${tool.name} in the workshop`}
        />
        <h2>Tips and suggestions</h2>
        <p>{tool.description}</p>

        <h2>Safety</h2>
        <p>{tool.safety}</p>

        <h2 id="report">Report a problem</h2>
        <form className={styles.form}>
          <div className={styles.inputGroup}>
            <label htmlFor="name">Name</label>
            <input type="text" name="name" className={styles.inputField} />
          </div>
          <div className={styles.inputGroup}>
            <label htmlFor="email">Email</label>
            <input type="email" name="email" className={styles.inputField} />
          </div>
          <div className={styles.inputGroup}>
            <label htmlFor="message">Message</label>
            <textarea rows="5" name="message" className={styles.inputField} />
          </div>
          <input type="submit" />
        </form>
      </main>
    </div>
  );
};

export default ToolPage;
